[package]
name = "dinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gimli = "0.28.1"
object = "0.32.1"
memmap2 = "0.9.0"
